# -*- coding: utf-8 -*-
"""q2chi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ojTi4HuSkvsCe4nib6Xx7G2ZezEZ9aCY
"""

import numpy as np
import pandas as pd

def readc(file_path):
    df = pd.read_csv(file_path, header=None, names=['No', 'X', 'Y', 'Z'])
    return df[['X', 'Y', 'Z']].values

def solve(dna, prot, t=0):
    dna = np.array(dna)
    prot = np.array(prot)
    v = []


    for p in prot:
        d = np.linalg.norm(dna - p, axis=1)
        visited_indices = np.where(d <= t)[0]
        v.extend(visited_indices)
    nv = len(v)

    for step, p in enumerate(prot):
        d = np.linalg.norm(dna - p, axis=1)
        if np.any(d <= t):
            fls = step + 1
            flp_index = np.argmin(d)
            flp = dna[flp_index]
            break
    else:
        fls = None
        flp = None


    if len(set(v)) > 1:
        min_index = min(v) + 1
        max_index = max(v) + 1
        mr = max_index - min_index
    else:
        mr = 0

    return nv, flp_index + 1, fls, mr

dna = readc('/content/DNA.csv')
prot = readc('/content/PROTIEN.csv')

nv, flp, fls, mr = solve(dna, prot)

print(f"Total site visits: {nv}")
print(f"First landing position index: {flp}")
print(f"First landing step: {fls}")
print(f"Max range: {mr}")
